const questionBank = [
  "If I were a transformer, my transformer name would be",
  "When no one is looking I like to",
  "This cartoon is the story of my life",
  "In a zombie apocalypse, this is the one thing I will take with me",
  "On a deserted island, I will miss this the most",
  "If I were a dictator, this is the crazy thing I will do",
  "If my bed sheets can be made of anything, it will be made of",
  "This would secretly be in my backyard",
  "If i can be anywhere right now, it would be",
  "My dream date consists of",
  "My dream wedding is at",
  "My soul animal is",
  "If I could be invisible, I would",
  "If I could erase one thing from existence then I would erase",
  "This would be my stripper name",
  "I don't usually steal from babies but when i do its because",
  "My nightly rate is",
  "If I could have a robot that will do this for me every day, it would be",
  "The title of the movie based on my life is",
  "If I could have any super power it would be",
  "If I could read minds, I would use it to",
  "If I could swap bodies with any person for 24 hours, I would swap with",
  "If i could tell my  12yr old self one thing, it would be",
  "This is my living nightmare",
  "My super hero name is",
  "My super villain name is",
  "I recently became famous from my youtube channel where I",
  "I recently met my future self, and they told me to watch out for",
  "If I won a million dollars, the first thing I would buy is",
]

module.exports = questionBank